import type {
  Alert,
  Check,
  FamilyCircle,
  GroupCircle,
  LiteracyLesson,
  QuarantinedMessage,
  ReportedEntity,
  SavedRecipient,
  ScamExample,
  ScamRadarEvent,
  TrustedContact,
  User,
  VerifiedInstitution,
} from '@/lib/types';

const now = Date.now();
const hours = (value: number) => now - value * 3_600_000;
const days = (value: number) => now - value * 86_400_000;

export const seedUser: User = {
  id: 'user-1',
  name: 'Amina Wanjiru',
  phone: '+254712345678',
  email: 'amina.wanjiru@example.co.ke',
  role: 'family-admin',
  county: 'Nairobi',
};

export const verifiedInstitutions: VerifiedInstitution[] = [
  {
    id: 'inst-kcb',
    name: 'KCB Bank Kenya',
    category: 'bank',
    officialNumbers: ['+254711087000', '+254732087000'],
    aliases: ['kcb', 'kcb bank'],
    note: 'KCB never asks for your PIN, OTP or full card number on a call.',
  },
  {
    id: 'inst-equity',
    name: 'Equity Bank Kenya',
    category: 'bank',
    officialNumbers: ['+254763000000'],
    aliases: ['equity', 'equity bank', 'equitel'],
    note: 'Equity staff will never ask you to move money to a "safe" account.',
  },
  {
    id: 'inst-coop',
    name: 'Co-operative Bank',
    category: 'bank',
    officialNumbers: ['+254703027000'],
    aliases: ['co-op bank', 'coop bank', 'cooperative bank'],
  },
  {
    id: 'inst-safaricom',
    name: 'Safaricom',
    category: 'telco',
    officialNumbers: ['+254722000100', '100'],
    aliases: ['safaricom', 'm-pesa', 'mpesa'],
    note: 'Safaricom care never asks for your M-Pesa PIN or a code sent to you.',
  },
  {
    id: 'inst-dci',
    name: 'DCI Kenya',
    category: 'government',
    officialNumbers: ['+254800722203'],
    aliases: ['dci', 'police', 'court', 'officer'],
    note: 'Police do not collect fines or bail through M-Pesa to personal numbers.',
  },
  {
    id: 'inst-nhif',
    name: 'SHA (formerly NHIF)',
    category: 'government',
    officialNumbers: ['+254800720601'],
    aliases: ['nhif', 'sha'],
  },
];

export const trustedContacts: TrustedContact[] = [
  {
    id: 'contact-1',
    name: 'Brian Wanjiru',
    relationship: 'Son',
    phone: '+254701998112',
    verified: true,
  },
  {
    id: 'contact-2',
    name: 'Mary Wanjiru',
    relationship: 'Mum',
    phone: '+254722114455',
    verified: true,
  },
  {
    id: 'contact-3',
    name: 'Joseph Otieno',
    relationship: 'Brother',
    phone: '+254733220087',
    verified: true,
  },
  {
    id: 'contact-4',
    name: 'Grace Kilonzo',
    relationship: 'Chama treasurer',
    phone: '+254720445566',
    verified: false,
  },
];

export const reportedEntities: ReportedEntity[] = [
  {
    identifier: '790125',
    identifierType: 'paybill',
    displayName: 'Paybill 790125',
    riskLevel: 'red',
    scamCategory: 'fake-bank-rep',
    reportCount: 14,
    uniqueReporters: 11,
    firstReportedAt: days(41),
    lastReportedAt: hours(9),
    reviewStatus: 'confirmed',
    merchantVerified: false,
    notes: [
      'Paybill registered 12 days ago.',
      'Not linked to any bank in our verified institution list.',
    ],
  },
  {
    identifier: '+254799001122',
    identifierType: 'phone',
    displayName: '+254 799 001 122',
    riskLevel: 'red',
    scamCategory: 'mpesa-reversal',
    reportCount: 23,
    uniqueReporters: 19,
    firstReportedAt: days(66),
    lastReportedAt: hours(4),
    reviewStatus: 'confirmed',
    notes: ['Reported from 7 counties.', 'Number is a personal line, not a registered business.'],
  },
  {
    identifier: '+254780554433',
    identifierType: 'phone',
    displayName: '+254 780 554 433',
    riskLevel: 'amber',
    scamCategory: 'fake-delivery',
    reportCount: 3,
    uniqueReporters: 3,
    firstReportedAt: days(12),
    lastReportedAt: days(2),
    reviewStatus: 'under-review',
    notes: ['Number first seen 12 days ago.'],
  },
  {
    identifier: '522533',
    identifierType: 'paybill',
    displayName: 'Paybill 522533',
    riskLevel: 'amber',
    scamCategory: 'none',
    reportCount: 0,
    uniqueReporters: 0,
    firstReportedAt: days(5),
    lastReportedAt: days(5),
    reviewStatus: 'unreviewed',
    merchantVerified: false,
    notes: ['Paybill created 5 days ago.', 'Not in our verified merchant list yet.'],
  },
  {
    identifier: '400200',
    identifierType: 'paybill',
    displayName: 'Co-operative Bank — Paybill 400200',
    riskLevel: 'blue',
    scamCategory: 'none',
    reportCount: 0,
    uniqueReporters: 0,
    firstReportedAt: days(1400),
    lastReportedAt: days(1400),
    reviewStatus: 'confirmed',
    merchantVerified: true,
    notes: ['Matches a verified institution in the Dhibiti directory.'],
  },
  {
    identifier: 'https://mpesa-secure-refund.com/verify',
    identifierType: 'url',
    displayName: 'mpesa-secure-refund.com',
    riskLevel: 'red',
    scamCategory: 'qr-merchant-phishing',
    reportCount: 9,
    uniqueReporters: 8,
    firstReportedAt: days(4),
    lastReportedAt: hours(2),
    reviewStatus: 'confirmed',
    domainAgeDays: 4,
    notes: [
      'Link redirects 3 times before reaching the final page.',
      'TLS certificate organisation does not match Safaricom PLC.',
      'Page contains a PIN entry form styled like M-Pesa.',
    ],
  },
  {
    identifier: 'https://invoice-pay.kcb-login.com/pay/8842',
    identifierType: 'url',
    displayName: 'invoice-pay.kcb-login.com',
    riskLevel: 'red',
    scamCategory: 'qr-merchant-phishing',
    reportCount: 6,
    uniqueReporters: 5,
    firstReportedAt: days(5),
    lastReportedAt: hours(20),
    reviewStatus: 'confirmed',
    domainAgeDays: 5,
    notes: [
      'Domain registered 5 days ago.',
      'Login form submits to a different domain than the one shown.',
    ],
  },
  {
    identifier: '0x8f2c19b4e77d3a5510cc',
    identifierType: 'crypto',
    displayName: 'USDT wallet 0x8f2c…10cc',
    riskLevel: 'red',
    scamCategory: 'crypto-investment',
    reportCount: 11,
    uniqueReporters: 9,
    firstReportedAt: days(30),
    lastReportedAt: days(1),
    reviewStatus: 'confirmed',
    notes: ['Crypto transfers cannot be reversed once confirmed.'],
  },
  {
    identifier: '888880',
    identifierType: 'till',
    displayName: 'Till 888880 — Mama Ndugu Groceries',
    riskLevel: 'green',
    scamCategory: 'none',
    reportCount: 0,
    uniqueReporters: 0,
    firstReportedAt: days(500),
    lastReportedAt: days(500),
    reviewStatus: 'unreviewed',
    merchantVerified: true,
    notes: ['Active for over a year with no reports.'],
  },
];

export const literacyLessons: LiteracyLesson[] = [
  {
    id: 'lesson-reversal',
    title: 'How the M-Pesa reversal scam works',
    category: 'scam-patterns',
    durationLabel: '60 sec',
    intro:
      'This scam is designed to trick anyone. It works by making you feel you owe someone money you never received.',
    bullets: [
      'You get a message or call saying money was sent to you by mistake.',
      'The "sender" is upset and in a hurry, so you feel pressure to fix it.',
      'You are asked to send it to a different number or Paybill — not the one that supposedly sent it.',
      'Check your real M-Pesa balance and statement before you move anything.',
      'A genuine wrong transfer is reversed by Safaricom, not by you sending money back.',
    ],
    example: {
      label: 'Real example, redacted',
      text: 'Nimetuma pesa kwako kimakosa. Tafadhali nirudishie haraka kwa 0799 XXX 122, nina shida.',
    },
    relatedScamCategory: 'mpesa-reversal',
  },
  {
    id: 'lesson-bank-impersonation',
    title: 'When someone calls claiming to be your bank',
    category: 'banks-merchants',
    durationLabel: '60 sec',
    intro:
      'Bank impersonation works because it borrows real authority. Knowing how banks actually behave removes that power.',
    bullets: [
      'A bank never asks for your PIN, full card number, OTP or password.',
      'A bank never asks you to move money to a "safe" or "holding" account.',
      'Caller ID can be faked, so the number on your screen proves nothing.',
      'Hang up and call the bank on the number saved in Dhibiti or printed on your card.',
      'If a caller resists you hanging up to verify, that is the strongest sign it is a scam.',
    ],
    relatedScamCategory: 'fake-bank-rep',
  },
  {
    id: 'lesson-qr-phishing',
    title: 'Why QR codes need checking before you scan-and-pay',
    category: 'scam-patterns',
    durationLabel: '75 sec',
    intro: 'A QR code hides its destination. That is convenient for you and useful for scammers.',
    bullets: [
      'A QR code can hold a link, a Paybill, a phone number or a wallet address — you cannot see which by looking.',
      'Fake merchant codes are printed over real ones or sent as "invoices" on WhatsApp.',
      'Look at the domain after scanning, not the logo on the poster.',
      'Never enter your PIN or ID number on a page you reached from a QR code.',
      'If the code was sent to you by someone in a hurry, treat it as unverified.',
    ],
    relatedScamCategory: 'qr-merchant-phishing',
  },
  {
    id: 'lesson-family-emergency',
    title: 'The family emergency script',
    category: 'scam-patterns',
    durationLabel: '45 sec',
    intro: 'This scam works on love, not greed. It targets parents and grandparents most often.',
    bullets: [
      'The message claims a relative is arrested, in hospital or stranded.',
      'It asks for secrecy so you cannot confirm with anyone else.',
      'The number is always new or "borrowed from a friend".',
      'Call your relative on the number you already have saved. Always.',
      'Agree a simple family rule: no money moves on a message alone.',
    ],
    example: {
      label: 'Real example, redacted',
      text: 'Mum niko police station Kasarani, nisaidie 15,000 haraka. Usimwambie mtu tafadhali.',
    },
    relatedScamCategory: 'family-emergency',
  },
  {
    id: 'lesson-prize',
    title: 'Prize and promotion scams',
    category: 'scam-patterns',
    durationLabel: '40 sec',
    intro: 'Many people in Kenya receive these messages. Most are scams.',
    bullets: [
      'You cannot win a promotion you never entered.',
      'A real prize never requires a fee to be released.',
      'Scammers use real brand names and logos freely.',
      "Confirm promotions on the brand's official channels, never through the message link.",
    ],
    relatedScamCategory: 'prize-lottery',
  },
  {
    id: 'lesson-sim-swap',
    title: 'SIM-swap basics',
    category: 'mobile-money',
    durationLabel: '60 sec',
    intro:
      'If someone controls your line, they can reach your mobile money. Protecting the line protects the money.',
    bullets: [
      'Never approve a SIM replacement you did not request.',
      'Never share codes sent to your phone, even with "customer care".',
      'If your line suddenly loses service, check with your provider immediately.',
      'Use a PIN on your SIM as well as on your phone.',
    ],
    relatedScamCategory: 'sim-swap',
  },
  {
    id: 'lesson-paybill-basics',
    title: 'Personal number vs Paybill vs Till',
    category: 'mobile-money',
    durationLabel: '75 sec',
    intro: 'Knowing which one you are paying tells you a lot about who is on the other side.',
    bullets: [
      'A personal number belongs to an individual, and a business asking you to pay one is a warning sign.',
      'A Paybill has an account number field — the account tells the business who paid.',
      'A Till is for buy-goods payments at a merchant point.',
      'Registered businesses have a consistent, published Paybill or Till. It does not change weekly.',
      'A brand-new Paybill claiming to be a large institution deserves a phone call first.',
    ],
    relatedScamCategory: 'fake-bank-rep',
  },
  {
    id: 'lesson-confirmation-messages',
    title: 'What a real M-Pesa confirmation looks like',
    category: 'mobile-money',
    durationLabel: '50 sec',
    intro:
      'Fake confirmation messages are easy to send. Real ones have properties a forwarded screenshot does not.',
    bullets: [
      'Real confirmations come from the M-PESA sender ID, in your existing message thread.',
      'They contain a transaction code, the exact amount, the name and your new balance.',
      'A screenshot proves nothing — check your own balance instead.',
      'Reversals are handled by Safaricom, and only within their own rules and window.',
    ],
    relatedScamCategory: 'mpesa-reversal',
  },
  {
    id: 'lesson-merchant-checks',
    title: 'Checking that a business is real',
    category: 'banks-merchants',
    durationLabel: '2 min',
    intro: 'Most online-shopping losses come from businesses with no verifiable presence.',
    bullets: [
      'Look for a physical address, a landline or a long-standing social presence.',
      'A business licence number can be checked with the county.',
      'Pay to a Till or Paybill in the business name, not a personal number.',
      'Be wary of prices far below market, and of pressure to pay a deposit today.',
      'Ask for the official number and call it from your own dialler.',
    ],
    relatedScamCategory: 'fake-delivery',
  },
  {
    id: 'lesson-recourse',
    title: 'If you have already sent money',
    category: 'rights-recourse',
    durationLabel: '2 min',
    intro:
      'Acting fast matters, and so does keeping evidence. Recovery is possible sometimes, not always — that is the honest position.',
    bullets: [
      'Call your provider immediately: Safaricom on 100, or your bank fraud desk.',
      'Report to the DCI and get an OB number from the nearest police station.',
      'Keep screenshots, transaction codes, numbers and times.',
      'Report the number or Paybill in Dhibiti so others are warned.',
      'Be careful of "recovery agents" who ask for a fee — that is a second scam.',
    ],
    relatedScamCategory: 'none',
  },
  {
    id: 'lesson-reports-help',
    title: 'How your report protects other people',
    category: 'rights-recourse',
    durationLabel: '45 sec',
    intro: 'One report becomes a warning for everyone who checks that number next.',
    bullets: [
      'Reports are aggregated and counted by unique reporter, so no single person can label a number alone.',
      'Identifiers are stored, not your message content, unless you explicitly share it.',
      'When several people report the same Paybill, it moves to confirmed status.',
      'Confirmed identifiers power Scam Radar warnings in your county.',
    ],
    relatedScamCategory: 'none',
  },
  {
    id: 'lesson-family-talk',
    title: 'How to talk to parents about scams',
    category: 'rights-recourse',
    durationLabel: '90 sec',
    intro: 'Shame keeps people silent, and silence is what scammers need. Start from respect.',
    bullets: [
      'Never open with "don\'t be careless" — open with "this one nearly caught me too".',
      'Agree one family rule: we always call each other back on saved numbers.',
      'Set a family code word for real emergencies.',
      'Make it normal to check with you before sending money, with no judgement.',
      'Set up Dhibiti alerts together so consent is clear.',
    ],
    relatedScamCategory: 'family-emergency',
  },
];

export const scamExamples: ScamExample[] = [
  {
    id: 'example-1',
    text_sw: 'Nimetuma pesa kwako kimakosa, tafadhali nirudishie kwa namba hii haraka.',
    text_en: 'I sent money to you by mistake, please send it back to this number urgently.',
    scamType: 'mpesa-reversal',
    riskLevel: 'red',
    patterns: ['reversal-claim', 'urgency', 'new-destination'],
    notes: 'Check your own balance. Real reversals are handled by Safaricom.',
  },
  {
    id: 'example-2',
    text_sw: 'Habari, ni KCB. Akaunti yako imefungwa. Nitumie code uliyopata ili tufungue.',
    text_en:
      'Hello, this is KCB. Your account is blocked. Send me the code you received so we can unblock it.',
    scamType: 'fake-bank-rep',
    riskLevel: 'red',
    patterns: ['impersonation', 'authority-threat', 'credential-request'],
    notes: 'No bank ever asks for a code. Call the bank on its official number.',
  },
  {
    id: 'example-3',
    text_sw: 'Hongera! Umeshinda KES 250,000 kwa promo ya Safaricom. Lipa KES 500 ya usajili.',
    text_en:
      'Congratulations! You have won KES 250,000 in the Safaricom promo. Pay KES 500 registration.',
    scamType: 'prize-lottery',
    riskLevel: 'red',
    patterns: ['reward-bait', 'payment-pressure'],
    notes: 'A real prize never needs a fee.',
  },
  {
    id: 'example-4',
    text_sw: 'Mum niko police station, nisaidie 20,000 haraka. Usimwambie mtu.',
    text_en: 'Mum I am at the police station, help me with 20,000 quickly. Do not tell anyone.',
    scamType: 'family-emergency',
    riskLevel: 'red',
    patterns: ['emotional-pressure', 'urgency', 'secrecy'],
    notes: 'Call the relative on their saved number before anything else.',
  },
  {
    id: 'example-5',
    text_sw: 'M-PESA: Umepokea KES 1,500 kutoka JOHN MWANGI. Salio jipya ni KES 4,320.',
    text_en: 'M-PESA: You have received KES 1,500 from JOHN MWANGI. New balance is KES 4,320.',
    scamType: 'none',
    riskLevel: 'blue',
    patterns: [],
    notes:
      'Format and sender ID match a genuine M-Pesa confirmation. Still confirm the payment was expected.',
  },
  {
    id: 'example-6',
    text_sw: 'Kazi ya haraka Nairobi, mshahara 45,000. Tuma 700 ya usajili kwa 0780 554 433.',
    text_en: 'Quick job in Nairobi, salary 45,000. Send 700 registration fee to 0780 554 433.',
    scamType: 'fake-job-loan',
    riskLevel: 'red',
    patterns: ['reward-bait', 'payment-pressure', 'new-destination'],
    notes: 'Genuine employers do not charge you to be hired.',
  },
  {
    id: 'example-7',
    text_sw: 'Mzigo wako umefika. Lipa ada ya usafirishaji KES 350 kwa namba hii ili tuachilie.',
    text_en: 'Your parcel has arrived. Pay a delivery fee of KES 350 to this number to release it.',
    scamType: 'fake-delivery',
    riskLevel: 'amber',
    patterns: ['payment-pressure', 'new-destination'],
    notes: 'Confirm with the courier using the number on their official website.',
  },
  {
    id: 'example-8',
    text_sw: 'Dear customer, your Equity statement is ready. Log in at equity.co.ke to view.',
    text_en: 'Dear customer, your Equity statement is ready. Log in at equity.co.ke to view.',
    scamType: 'none',
    riskLevel: 'green',
    patterns: [],
    notes: 'No pressure, no payment request, official domain. Nothing known against it.',
  },
  {
    id: 'example-9',
    text_sw: 'Tumia paybill mpya 790125 kwa malipo ya leo. Ya zamani imefungwa.',
    text_en: "Use new paybill 790125 for today's payments. The old one is closed.",
    scamType: 'fake-bank-rep',
    riskLevel: 'red',
    patterns: ['new-destination', 'urgency'],
    notes: 'A switched payment destination is one of the strongest single warning signs.',
  },
  {
    id: 'example-10',
    text_sw: 'Invest 5,000 in USDT today and get guaranteed 30,000 in one week. Tuma haraka.',
    text_en: 'Invest 5,000 in USDT today and get a guaranteed 30,000 in one week. Send quickly.',
    scamType: 'crypto-investment',
    riskLevel: 'red',
    patterns: ['crypto-irreversible', 'reward-bait', 'urgency'],
    notes: 'Guaranteed returns do not exist, and crypto payments cannot be reversed.',
  },
];

export const scamRadarEvents: ScamRadarEvent[] = [
  {
    id: 'radar-1',
    scamCategory: 'mpesa-reversal',
    roughLocation: 'Nakuru',
    reportCountLast24h: 3,
    sampleAnonymizedSummary:
      '3 M-Pesa reversal messages reported in Nakuru today, all pointing to one personal number.',
    relatedLessonId: 'lesson-reversal',
    relatedInstitutionId: 'inst-safaricom',
  },
  {
    id: 'radar-2',
    scamCategory: 'fake-bank-rep',
    roughLocation: 'Nairobi',
    reportCountLast24h: 8,
    sampleAnonymizedSummary:
      'Fake KCB fraud-desk calls are spiking in Nairobi this week. Here is the real KCB number.',
    relatedLessonId: 'lesson-bank-impersonation',
    relatedInstitutionId: 'inst-kcb',
  },
  {
    id: 'radar-3',
    scamCategory: 'qr-merchant-phishing',
    roughLocation: 'Mombasa',
    reportCountLast24h: 4,
    sampleAnonymizedSummary:
      'QR "invoice" codes shared on WhatsApp in Mombasa are leading to a look-alike M-Pesa login page.',
    relatedLessonId: 'lesson-qr-phishing',
  },
  {
    id: 'radar-4',
    scamCategory: 'fake-job-loan',
    roughLocation: 'Kisumu',
    reportCountLast24h: 5,
    sampleAnonymizedSummary:
      '5 people in Kisumu reported job offers asking for a registration fee to a new number.',
    relatedLessonId: 'lesson-merchant-checks',
  },
];

export const seedFamilyCircle: FamilyCircle = {
  id: 'circle-1',
  adminUserId: 'user-1',
  members: [
    {
      userId: 'user-1',
      name: 'Amina Wanjiru (you)',
      phone: '+254712345678',
      role: 'admin',
      status: 'active',
      sharingLevel: 'alertsOnly',
    },
    {
      userId: 'user-2',
      name: 'Mary Wanjiru',
      phone: '+254722114455',
      role: 'protected',
      status: 'active',
      sharingLevel: 'withRecipient',
      lockSeconds: 900,
    },
    {
      userId: 'user-3',
      name: 'Joseph Otieno',
      phone: '+254733220087',
      role: 'protected',
      status: 'pending',
      sharingLevel: 'alertsOnly',
    },
  ],
};

export const seedGroupCircles: GroupCircle[] = [
  {
    id: 'group-1',
    name: 'Tumaini Chama',
    kind: 'chama',
    adminUserId: 'user-1',
    members: [
      {
        userId: 'user-1',
        name: 'Amina Wanjiru (you)',
        phone: '+254712345678',
        role: 'admin',
        status: 'active',
        sharingLevel: 'alertsOnly',
      },
      {
        userId: 'user-4',
        name: 'Grace Kilonzo',
        phone: '+254720445566',
        role: 'protected',
        status: 'active',
        sharingLevel: 'alertsOnly',
      },
      {
        userId: 'user-5',
        name: 'Peter Kamau',
        phone: '+254701223344',
        role: 'protected',
        status: 'active',
        sharingLevel: 'alertsOnly',
      },
      {
        userId: 'user-6',
        name: 'Faith Njeri',
        phone: '+254798112233',
        role: 'protected',
        status: 'pending',
        sharingLevel: 'alertsOnly',
      },
    ],
    broadcastAlerts: ['alert-group-1'],
  },
  {
    id: 'group-2',
    name: 'Jenga SACCO — Branch 4',
    kind: 'sacco',
    adminUserId: 'user-7',
    members: [
      {
        userId: 'user-7',
        name: 'Samuel Mutiso',
        phone: '+254711556677',
        role: 'admin',
        status: 'active',
        sharingLevel: 'alertsOnly',
      },
      {
        userId: 'user-1',
        name: 'Amina Wanjiru (you)',
        phone: '+254712345678',
        role: 'protected',
        status: 'active',
        sharingLevel: 'alertsOnly',
      },
    ],
    broadcastAlerts: [],
  },
];

export const seedChecks: Check[] = [
  {
    id: 'check-kcb-call',
    userId: 'user-1',
    type: 'call',
    inputSummary: 'Caller claiming to be the KCB fraud desk, asking for KES 20,000',
    inputText:
      'Caller said he is from KCB fraud department. Said my account will be blocked today and I must send KES 20,000 to Paybill 790125 immediately. He told me not to tell anyone at the branch.',
    riskLevel: 'red',
    recipientRiskLevel: 'red',
    recipientIdentifier: '790125',
    recipientIdentifierType: 'paybill',
    detectedPatterns: [
      {
        id: 'bank-impersonation',
        label: 'The caller claims to be a bank fraud desk.',
        category: 'impersonation',
        evidence: 'KCB fraud department',
        weight: 22,
      },
      {
        id: 'authority-threat',
        label: 'You are threatened that your account will be blocked.',
        category: 'authority-threat',
        evidence: 'account will be blocked',
        weight: 24,
      },
      {
        id: 'urgency',
        label: 'You are pushed to act immediately.',
        category: 'urgency',
        evidence: 'immediately',
        weight: 18,
      },
      {
        id: 'secrecy',
        label: 'You are told not to tell anyone.',
        category: 'secrecy',
        evidence: 'not to tell anyone',
        weight: 20,
      },
      {
        id: 'new-destination',
        label: 'You are told to pay a Paybill you have never used.',
        category: 'new-destination',
        evidence: 'Paybill 790125',
        weight: 20,
      },
    ],
    ruleScore: 96,
    scamCategory: 'fake-bank-rep',
    ruleFactLines: [
      'This interaction contains five warning signs associated with impersonation scams.',
      'Paybill 790125 has been reported 14 times for fake bank representative scams.',
      'Paybill 790125 was registered 12 days ago and is not linked to KCB.',
    ],
    aiExplanation:
      'Fraudsters often call pretending to be from a bank fraud desk, because people move fast when they think their account is at risk.',
    technicalDetails: [
      'Rule score: 96/100 (five matched rules, two combination boosts).',
      'Combination: claimed identity + money request.',
      'Combination: urgency + secrecy.',
      'Recipient lookup: paybill 790125, 11 unique reporters, confirmed status.',
    ],
    recommendedActions: [
      {
        id: 'a1',
        label: 'Call KCB Bank Kenya on its verified number',
        kind: 'call-verified',
        emphasis: 'primary',
        payload: 'inst-kcb',
        helper: 'Do not call the number that called you.',
      },
      {
        id: 'a2',
        label: 'Check this payment before sending',
        kind: 'safe-pay',
        emphasis: 'secondary',
        payload: '790125',
      },
      {
        id: 'a3',
        label: 'Report this call',
        kind: 'report',
        emphasis: 'secondary',
      },
    ],
    claimedIdentity: 'KCB Bank Kenya',
    relatedLessonId: 'lesson-bank-impersonation',
    createdAt: hours(3),
  },
  {
    id: 'check-qr-invoice',
    userId: 'user-1',
    type: 'qr',
    inputSummary: 'QR "invoice" from WhatsApp — invoice-pay.kcb-login.com',
    inputText: 'https://invoice-pay.kcb-login.com/pay/8842',
    riskLevel: 'red',
    recipientRiskLevel: 'red',
    recipientIdentifier: 'https://invoice-pay.kcb-login.com/pay/8842',
    recipientIdentifierType: 'url',
    qrContentType: 'url',
    detectedPatterns: [
      {
        id: 'lookalike-domain',
        label: 'The web address imitates a Kenyan bank but is not its official domain.',
        category: 'lookalike-domain',
        evidence: 'kcb-login.com',
        weight: 45,
      },
      {
        id: 'link-bait',
        label: 'The QR code leads straight to a payment page.',
        category: 'link-obfuscation',
        evidence: '/pay/8842',
        weight: 12,
      },
    ],
    ruleScore: 88,
    scamCategory: 'qr-merchant-phishing',
    ruleFactLines: [
      'This QR code leads to a login page that imitates KCB but uses a different domain.',
      'The domain was created 5 days ago.',
      '6 people have reported this link for QR or merchant phishing.',
    ],
    aiExplanation:
      'QR codes hide where they lead, so a code that opens a login or payment page for a brand you know is worth checking before you enter anything.',
    technicalDetails: [
      'Resolved host: invoice-pay.kcb-login.com',
      'Domain age: 5 days.',
      'Login form submits to a different domain than the one shown.',
      'Rule score: 88/100.',
    ],
    recommendedActions: [
      {
        id: 'b1',
        label: 'Open a safe, non-interactive preview',
        kind: 'browser',
        emphasis: 'primary',
        payload: 'https://invoice-pay.kcb-login.com/pay/8842',
        helper: 'Nothing you type is sent from the preview.',
      },
      {
        id: 'b2',
        label: 'Call KCB Bank Kenya on its verified number',
        kind: 'call-verified',
        emphasis: 'secondary',
        payload: 'inst-kcb',
      },
      {
        id: 'b3',
        label: 'Report this QR code',
        kind: 'report',
        emphasis: 'secondary',
      },
    ],
    claimedIdentity: 'KCB Bank Kenya',
    relatedLessonId: 'lesson-qr-phishing',
    createdAt: hours(26),
  },
  {
    id: 'check-reversal-sms',
    userId: 'user-2',
    type: 'sms',
    inputSummary: 'SMS claiming money was sent by mistake',
    inputText:
      'Nimetuma pesa kwako kimakosa. Tafadhali nirudishie haraka kwa 0799 001 122, nina shida. Usimwambie mtu.',
    riskLevel: 'red',
    recipientRiskLevel: 'red',
    recipientIdentifier: '+254799001122',
    recipientIdentifierType: 'phone',
    detectedPatterns: [
      {
        id: 'reversal-claim',
        label: 'Someone claims money was sent to you by mistake.',
        category: 'reversal-claim',
        evidence: 'umetuma pesa kwangu kimakosa',
        weight: 30,
      },
      {
        id: 'urgency',
        label: 'The message pushes you to act immediately.',
        category: 'urgency',
        evidence: 'haraka',
        weight: 18,
      },
      {
        id: 'secrecy',
        label: 'You are asked to keep this from other people.',
        category: 'secrecy',
        evidence: 'usimwambie mtu',
        weight: 20,
      },
    ],
    ruleScore: 84,
    scamCategory: 'mpesa-reversal',
    ruleFactLines: [
      'This message matches a common M-Pesa reversal scam.',
      '+254 799 001 122 has been reported 23 times by 19 different people.',
      'The number is a personal line, not a registered business.',
    ],
    aiExplanation:
      'This looks like a scam where fraudsters claim you received money by mistake and ask you to send it back to a different number, so your own money leaves your account.',
    technicalDetails: [
      'Rule score: 84/100 (three matched rules, urgency + secrecy combination).',
      'Language: Kiswahili, matched Kiswahili rule set.',
      'Recipient lookup: 19 unique reporters across 7 counties.',
    ],
    recommendedActions: [
      {
        id: 'c1',
        label: 'Call Brian Wanjiru (Son) on his saved number',
        kind: 'call-contact',
        emphasis: 'primary',
        payload: 'contact-1',
        helper: 'Talk to family before moving any money.',
      },
      {
        id: 'c2',
        label: 'Report this number',
        kind: 'report',
        emphasis: 'secondary',
      },
      {
        id: 'c3',
        label: 'Learn how this scam works (60 sec)',
        kind: 'lesson',
        emphasis: 'secondary',
        payload: 'lesson-reversal',
      },
    ],
    relatedLessonId: 'lesson-reversal',
    createdAt: hours(30),
  },
  {
    id: 'check-shop-till',
    userId: 'user-1',
    type: 'number',
    inputSummary: 'Till 888880 — Mama Ndugu Groceries',
    riskLevel: 'green',
    recipientRiskLevel: 'green',
    recipientIdentifier: '888880',
    recipientIdentifierType: 'till',
    detectedPatterns: [],
    ruleScore: 0,
    scamCategory: 'none',
    ruleFactLines: [
      'No reports found for Till 888880.',
      'This Till has been active for over a year.',
    ],
    aiExplanation:
      'Nothing is known against this Till, but that is not a guarantee — confirm the amount matches what you agreed.',
    technicalDetails: ['Community lookup: 0 reports.', 'Merchant verification: verified merchant.'],
    recommendedActions: [
      {
        id: 'd1',
        label: 'Verify a payment before sending',
        kind: 'safe-pay',
        emphasis: 'primary',
        payload: '888880',
      },
      {
        id: 'd2',
        label: 'Report this Till',
        kind: 'report',
        emphasis: 'secondary',
      },
    ],
    createdAt: days(2),
  },
  {
    id: 'check-safaricom-sms',
    userId: 'user-1',
    type: 'sms',
    inputSummary: 'M-PESA confirmation from the official sender ID',
    inputText: 'M-PESA: Umepokea KES 1,500 kutoka JOHN MWANGI. Salio jipya ni KES 4,320.',
    riskLevel: 'blue',
    detectedPatterns: [],
    ruleScore: 0,
    scamCategory: 'none',
    ruleFactLines: [
      'The sender ID matches Safaricom M-PESA in our verified directory.',
      'The message contains no payment request, link or code request.',
    ],
    aiExplanation:
      'The format matches a genuine confirmation, so the next step is simply to confirm you were expecting this payment.',
    technicalDetails: ['Sender ID matched verified shortcode list.', 'Rule score: 0/100.'],
    recommendedActions: [
      {
        id: 'e1',
        label: 'Confirm the payment was expected',
        kind: 'dismiss',
        emphasis: 'primary',
        helper: 'Check your own balance rather than trusting a forwarded screenshot.',
      },
      {
        id: 'e2',
        label: 'Learn what real confirmations look like',
        kind: 'lesson',
        emphasis: 'secondary',
        payload: 'lesson-confirmation-messages',
      },
    ],
    relatedLessonId: 'lesson-confirmation-messages',
    createdAt: days(3),
  },
];

export const seedAlerts: Alert[] = [
  {
    id: 'alert-1',
    circleId: 'circle-1',
    circleKind: 'family',
    relatedCheckId: 'check-reversal-sms',
    memberName: 'Mary Wanjiru',
    summary: 'Mary received a high-risk M-Pesa reversal message',
    detail:
      'The message claims money was sent by mistake and asks her to send it to +254 799 001 122, a number reported 23 times.',
    riskLevel: 'red',
    suggestedAction: 'Call Mary on her saved number and confirm she has not sent anything.',
    contactPhone: '+254722114455',
    createdAt: hours(30),
  },
  {
    id: 'alert-2',
    circleId: 'circle-1',
    circleKind: 'family',
    relatedCheckId: 'check-qr-invoice',
    memberName: 'Mary Wanjiru',
    summary: 'Mary scanned a QR code flagged as high risk for phishing',
    detail:
      'The code led to invoice-pay.kcb-login.com, a 5-day-old domain imitating KCB. She did not enter anything.',
    riskLevel: 'red',
    suggestedAction: 'Confirm she has not entered her PIN anywhere, and share the real KCB number.',
    contactPhone: '+254722114455',
    createdAt: hours(26),
  },
  {
    id: 'alert-group-1',
    circleId: 'group-1',
    circleKind: 'group',
    memberName: 'Tumaini Chama',
    summary: 'Broadcast: someone is impersonating the chama treasurer',
    detail:
      'Members received a message claiming contributions must now go to Paybill 790125. The real collection details have not changed.',
    riskLevel: 'red',
    suggestedAction: 'Do not pay any new Paybill. Confirm with the treasurer on her saved number.',
    contactPhone: '+254720445566',
    createdAt: hours(8),
  },
];

export const seedQuarantine: QuarantinedMessage[] = [
  {
    id: 'quar-1',
    sender: '+254799001122',
    body: 'Nimetuma pesa kwako kimakosa. Nirudishie haraka kwa namba hii, usimwambie mtu.',
    reason: 'Matches M-Pesa reversal pattern. Sender reported 23 times.',
    riskLevel: 'red',
    receivedAt: hours(5),
    status: 'quarantined',
  },
  {
    id: 'quar-2',
    sender: 'PROMO-KE',
    body: 'Hongera! Umeshinda KES 250,000. Lipa KES 500 ya usajili kwa paybill 522533.',
    reason: 'Prize bait combined with an upfront fee to a 5-day-old Paybill.',
    riskLevel: 'red',
    receivedAt: hours(19),
    status: 'quarantined',
  },
  {
    id: 'quar-3',
    sender: '+254780554433',
    body: 'Mzigo wako umefika. Lipa ada ya usafirishaji KES 350 kwa namba hii.',
    reason: 'Delivery fee requested to a personal number first seen 12 days ago.',
    riskLevel: 'amber',
    receivedAt: days(1),
    status: 'quarantined',
  },
];

export const seedRecipients: SavedRecipient[] = [
  {
    id: 'rec-1',
    label: 'Mama Ndugu Groceries',
    identifier: '888880',
    identifierType: 'till',
    riskLevel: 'green',
    timesPaid: 12,
    lastPaidAt: days(4),
  },
  {
    id: 'rec-2',
    label: 'Co-operative Bank — my account',
    identifier: '400200',
    identifierType: 'paybill',
    riskLevel: 'blue',
    timesPaid: 26,
    lastPaidAt: days(11),
  },
  {
    id: 'rec-3',
    label: 'Brian (school fees)',
    identifier: '+254701998112',
    identifierType: 'phone',
    riskLevel: 'green',
    timesPaid: 8,
    lastPaidAt: days(20),
  },
  {
    id: 'rec-4',
    label: 'New landlord Paybill',
    identifier: '522533',
    identifierType: 'paybill',
    riskLevel: 'amber',
    timesPaid: 0,
  },
];

export type QrSample = {
  id: string;
  label: string;
  raw: string;
};

/** Camera capture is simulated in this build; these stand in for real scans. */
export const qrSamples: QrSample[] = [
  {
    id: 'qr-invoice',
    label: 'WhatsApp "invoice" code',
    raw: 'https://invoice-pay.kcb-login.com/pay/8842',
  },
  {
    id: 'qr-refund',
    label: 'M-Pesa "refund" code',
    raw: 'https://mpesa-secure-refund.com/verify?ref=88213',
  },
  {
    id: 'qr-paybill',
    label: 'Poster Paybill code',
    raw: 'Paybill 522533 account RENT2026 amount KES 18,000',
  },
  {
    id: 'qr-shop',
    label: 'Shop counter Till code',
    raw: 'Till 888880 buy goods Mama Ndugu Groceries',
  },
  {
    id: 'qr-crypto',
    label: 'Investment group code',
    raw: 'USDT 0x8f2c19b4e77d3a5510cc amount 5000 guaranteed returns',
  },
  {
    id: 'qr-wifi',
    label: 'Cafe Wi-Fi code',
    raw: 'WIFI:S:Free Wifi Airport;T:nopass;P:;;',
  },
];

export const paymentTips = [
  {
    id: 'tip-1',
    title: 'Pay businesses, not people',
    body: 'A registered business collects on a Paybill or Till in its own name.',
    lessonId: 'lesson-paybill-basics',
  },
  {
    id: 'tip-2',
    title: 'Never pay to unlock a prize',
    body: 'Fees to release winnings are always a scam, whatever brand is named.',
    lessonId: 'lesson-prize',
  },
  {
    id: 'tip-3',
    title: 'Call back on your own number',
    body: 'Caller ID can be faked. Use the number you already have saved.',
    lessonId: 'lesson-bank-impersonation',
  },
  {
    id: 'tip-4',
    title: 'Already sent money?',
    body: 'Act in the first hour: provider, police OB number, keep evidence.',
    lessonId: 'lesson-recourse',
  },
];
